#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
FFI_DIR="$PROJECT_DIR/rhwp-ffi"
OUTPUT_DIR="$PROJECT_DIR/libs"
CARGO="${CARGO:-/opt/homebrew/bin/cargo}"
RUSTUP="${RUSTUP:-/opt/homebrew/opt/rustup/bin/rustup}"

echo "Building rhwp-ffi static library (universal: arm64 + x86_64)..."
echo "  FFI_DIR:    $FFI_DIR"
echo "  OUTPUT_DIR: $OUTPUT_DIR"

mkdir -p "$OUTPUT_DIR"

# The rhwp git dependency ships its own rust-toolchain.toml (pinned to an
# older channel for its own wasm32 dev workflow). Cargo runs each crate's
# rustc invocation with cwd set to that crate's own source root, so when
# rustup's rustc/cargo proxies resolve the toolchain from cwd, compiling
# rhwp itself picks up its pinned channel instead of ours — producing a
# rustc-version mismatch (E0514) against every other dependency in the
# graph. Resolving RUSTC to an absolute path up front bypasses the proxies'
# cwd-based lookup for every rustc invocation in this build, keeping the
# whole dependency graph on one consistent compiler.
if [ -z "${RUSTC:-}" ] && [ -x "$RUSTUP" ]; then
    RUSTC="$(cd "$FFI_DIR" && "$RUSTUP" which rustc)"
fi
export RUSTC

TARGETS=(aarch64-apple-darwin x86_64-apple-darwin)

# Run target queries from FFI_DIR so they resolve against the same toolchain
# the build itself uses (rustup honors per-directory overrides by cwd).
if [ -x "$RUSTUP" ]; then
    INSTALLED_TARGETS="$(cd "$FFI_DIR" && "$RUSTUP" target list --installed)"
    for TARGET in "${TARGETS[@]}"; do
        if ! grep -qx "$TARGET" <<<"$INSTALLED_TARGETS"; then
            echo "Installing missing target: $TARGET"
            (cd "$FFI_DIR" && "$RUSTUP" target add "$TARGET")
        fi
    done
fi

ARTIFACTS=()
for TARGET in "${TARGETS[@]}"; do
    echo ""
    echo "-- Building for $TARGET --"
    (cd "$FFI_DIR" && $CARGO build --release --target "$TARGET")
    ARTIFACTS+=("$FFI_DIR/target/$TARGET/release/librhwp_ffi.a")
done

OUT_A="$OUTPUT_DIR/libhwp_ffi.a"
lipo -create "${ARTIFACTS[@]}" -output "$OUT_A"

# Extract pinned rhwp revision from Cargo.toml (source of truth).
RHWP_REV=$(awk -F'"' '/^rhwp = /{for(i=1;i<=NF;i++) if($i=="rev = ") print $(i+1)}' "$FFI_DIR/Cargo.toml")
if [ -z "${RHWP_REV:-}" ]; then
    RHWP_REV=$(grep -Eo 'rev = "[^"]+"' "$FFI_DIR/Cargo.toml" | head -1 | awk -F'"' '{print $2}')
fi
RHWP_REPO=$(grep -Eo 'git = "[^"]+"' "$FFI_DIR/Cargo.toml" | head -1 | awk -F'"' '{print $2}')
BUILT_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
SHA=$(shasum -a 256 "$OUT_A" | awk '{print $1}')
SIZE=$(stat -f%z "$OUT_A")
ARCHS=$(lipo -archs "$OUT_A")

cat > "$OUTPUT_DIR/rhwp.lock" <<EOF
# Auto-generated by scripts/build-rust.sh — do not edit by hand.
repo:      $RHWP_REPO
commit:    $RHWP_REV
built_at:  $BUILT_AT
artifact:  libhwp_ffi.a
archs:     $ARCHS
sha256:    $SHA
size:      $SIZE
EOF

echo ""
echo "Done."
echo "  Static library: $OUT_A"
echo "  Metadata:       $OUTPUT_DIR/rhwp.lock"
echo ""
cat "$OUTPUT_DIR/rhwp.lock"
