#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
FFI_DIR="$PROJECT_DIR/rhwp-ffi"
OUTPUT_DIR="$PROJECT_DIR/libs"
CARGO="${CARGO:-/opt/homebrew/bin/cargo}"

echo "Building rhwp-ffi static library..."
echo "  FFI_DIR:    $FFI_DIR"
echo "  OUTPUT_DIR: $OUTPUT_DIR"

mkdir -p "$OUTPUT_DIR"
(cd "$FFI_DIR" && $CARGO build --release)

OUT_A="$OUTPUT_DIR/libhwp_ffi.a"
cp "$FFI_DIR/target/release/librhwp_ffi.a" "$OUT_A"

# Extract pinned rhwp revision from Cargo.toml (source of truth).
RHWP_REV=$(awk -F'"' '/^rhwp = /{for(i=1;i<=NF;i++) if($i=="rev = ") print $(i+1)}' "$FFI_DIR/Cargo.toml")
if [ -z "${RHWP_REV:-}" ]; then
    RHWP_REV=$(grep -Eo 'rev = "[^"]+"' "$FFI_DIR/Cargo.toml" | head -1 | awk -F'"' '{print $2}')
fi
RHWP_REPO=$(grep -Eo 'git = "[^"]+"' "$FFI_DIR/Cargo.toml" | head -1 | awk -F'"' '{print $2}')
BUILT_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
SHA=$(shasum -a 256 "$OUT_A" | awk '{print $1}')
SIZE=$(stat -f%z "$OUT_A")

cat > "$OUTPUT_DIR/rhwp.lock" <<EOF
# Auto-generated by scripts/build-rust.sh — do not edit by hand.
repo:      $RHWP_REPO
commit:    $RHWP_REV
built_at:  $BUILT_AT
artifact:  libhwp_ffi.a
sha256:    $SHA
size:      $SIZE
EOF

echo ""
echo "Done."
echo "  Static library: $OUT_A"
echo "  Metadata:       $OUTPUT_DIR/rhwp.lock"
echo ""
cat "$OUTPUT_DIR/rhwp.lock"
